---
title: "ANA 515 Assignemnt 1"
date: "2022-08-28"
output: 
   html_document:
          theme:
              bootswatch: cyborg
---

```{r setup, include=FALSE}
install.packages("bslib", repos = "http://cran.us.r-project.org")
install.packages("tidyverse", repos = "http://cran.us.r-project.org")
install.packages("knitr", repos = "http://cran.us.r-project.org")
install.packages("readr", repos = "http://cran.us.r-project.org")
library(ggplot2)
library(dplyr)
library(readr)
library(tidyverse)
```


```{r, include = FALSE}
#this next line is creating a subset called 'smaller' of the diamonds data
url <- "https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv"
guns <- read_csv(url)
```

```{r, echo = FALSE}
youth <- guns %>% 
  filter(age <= 65)
```

```{r youth, include=FALSE}
summary(youth)
```

```{r, echo = FALSE}
#This next chunk is inline code. Inline code puts the text with the output of the function in my document.
```

We have data about `r nrow(guns)` individuals killed by guns. Only 
`r nrow(guns) - nrow(youth)` are older than 65. The distribution of the remainder is shown
below:

``` {r, echo = FALSE}
#This next code chunk will make a plot in our output doc
```

```{r, echo = FALSE}
youth %>% 
  ggplot(aes(age)) + 
  geom_freqpoly(binwidth = 1)
```

```{r race-dist, echo=FALSE}
youth %>%
  ggplot(aes(fct_infreq(race) %>% fct_rev())) + geom_bar() + coord_flip() +
  labs(x = "Victim race")
```





